In [171]:
import numpy as np

In [172]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [173]:
# How many negative numbers are there?

In [174]:
len(a[a  < 0])

4

In [175]:
# How many positive numbers are there?

In [176]:
len(a[a > 0])

5

In [177]:
# If you were to add 3 to each data point, how many positive numbers would there be

In [178]:
a += 3
len(a[a > 0])

10

In [179]:
# If you squared each number, what would the new mean and standard deviation be?

In [180]:
a = a ** 2

In [181]:
a

array([ 49, 169, 225, 676,   1,   4,   9,   9,   9,   9,  36,  16])

In [182]:
np.mean(a)

101.0

In [183]:
np.std(a)

186.64672512530188

In [184]:
# A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

In [185]:
a = a - a / np.mean(a)

In [186]:
# Calculate the z-score for each data point. Recall that the z-score is given by:

In [187]:
a - np.mean(a) / np.std(a)

array([4.79737222e+01, 1.66785603e+02, 2.22231148e+02, 6.68765801e+02,
       4.48969773e-01, 3.41926680e+00, 8.36976185e+00, 8.36976185e+00,
       8.36976185e+00, 8.36976185e+00, 3.51024351e+01, 1.53004549e+01])

# number 8

In [60]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [ ]:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [43]:
sum_of_a = np.sum(a)

In [ ]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [45]:
min_of_a = np.min(a)

In [ ]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [46]:
max_of_a = np.max(a)

In [ ]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [47]:
mean_of_a = np.mean(a)

In [ ]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [48]:
product_of_a = np.product(a)

In [119]:
product_of_a

3628800

In [ ]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [50]:
squares_of_a = np.square(a)

In [ ]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

In [61]:
odds_in_a = a[a % 2 == 1]

In [ ]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [62]:
evens_in_a = a[a % 2 == 0]

# section 2

In [191]:
b = np.array([
    [3, 4, 5],
    [6, 7, 8]
])


In [192]:
#sum_of_b = 0
#for row in b:
 #   sum_of_b += sum(row)

In [193]:
a = np.array(b)

In [194]:
a.sum()

33

In [195]:
# Exercise 2 - refactor the following to use numpy

In [196]:
a.min()

3

In [197]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.

In [198]:
a.max()

8

In [199]:
# Exercise 4 - refactor the following using numpy to find the mean of b

In [200]:
a.mean()

5.5

In [201]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.

In [202]:
a.prod()

20160

In [203]:
# Exercise 6 - refactor the following to use numpy to find the list of squares

In [204]:
np.square(a)

array([[ 9, 16, 25],
       [36, 49, 64]])

In [205]:
# Exercise 7 - refactor using numpy to determine the odds_in_b

In [206]:
odds_in_b = a[a % 2 == 1]
odds_in_b

array([3, 5, 7])

In [207]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers

In [208]:
evenss_in_b = a[a % 2 == 0]

In [209]:
# Exercise 9 - print out the shape of the array b.

In [210]:
a.shape


(2, 3)

In [ ]:
# Exercise 10 - transpose the array b.

In [101]:
a.transpose()

array([[3, 6],
       [4, 7],
       [5, 8]])

In [ ]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

In [102]:
a.reshape(1, 6)

array([[3, 4, 5, 6, 7, 8]])

In [ ]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [103]:
a.reshape(6, 1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

# section 3

In [105]:
c = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [ ]:
# Exercise 1 - Find the min, max, sum, and product of c.

In [108]:
c.min()

1

In [109]:
c.max()

9

In [110]:
c.sum()

45

In [111]:
c.prod()

362880

In [ ]:
# Exercise 2 - Determine the standard deviation of c.

In [106]:
c.std()

2.581988897471611

In [ ]:
# Exercise 3 - Determine the variance of c.

In [112]:
c.var()

6.666666666666667

In [ ]:
# Exercise 4 - Print out the shape of the array c

In [211]:
print(c)
print(c.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [ ]:
# Exercise 5 - Transpose c and print out transposed result.

In [219]:
transpose = c.transpose()

In [ ]:
# Exercise 6 - Get the dot product of the array c with c. 

In [118]:
np.dot(c, c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [ ]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

In [220]:
transpose_c = transpose *c 
np.sum(transpose_c)

261

In [ ]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.


In [ ]:
dot_prod_c = np.dot(c, c)
dot_prod_c

In [223]:
d =np.array([
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
])

In [ ]:
# Exercise 1 - Find the sine of all the numbers in d

In [224]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [ ]:
# Exercise 2 - Find the cosine of all the numbers in d

In [225]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [ ]:
# Exercise 3 - Find the tangent of all the numbers in d

In [226]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [ ]:
# Exercise 4 - Find all the negative numbers in d

In [231]:
d[d<0]

array([-90, -30, -45, -45])

In [ ]:
# Exercise 5 - Find all the positive numbers in d

In [230]:
d[d>0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [ ]:
# Exercise 6 - Return an array of only the unique numbers in d.

In [232]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [ ]:
# Exercise 7 - Determine how many unique numbers there are in d

In [234]:
np.count_nonzero(np.unique(d)) + np.count_nonzero(np.unique(d == 0))
len(np.unique(d))

11

In [ ]:
# Exercise 8 - Print out the shape of d.

In [237]:
print(d)
d.shape

[[ 90  30  45   0 120 180]
 [ 45 -90 -30 270  90   0]
 [ 60  45 -45  90 -45 180]]


(3, 6)

In [ ]:
# Exercise 9 - Transpose and then print out the shape of d.

In [241]:
np.transpose(d).shape

(6, 3)

In [ ]:
# Exercise 10 - Reshape d into an array of 9 x 2

In [242]:
d.reshape(9, 2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])